version: "3"
services:
  nodejs_fastify:
    build:
      context: .
    container_name: cube_nodejs_fastify
    environment:
      # tell the app that it is running in docker compose
      - CUBE_DOCKER_COMPOSE=true

      - ELASTIC_APM_SERVICE_NAME=cube_sample_nodejs_fastify_elastic
      - ELASTIC_APM_SERVER_URL=http://host.docker.internal:3130

      # optional settings
      # Elastic agent sets environment from NODE_ENV by default
      - ELASTIC_APM_ENVIRONMENT=UNSET
      # - ELASTIC_APM_SERVICE_VERSION=1.2.3
      # - ELASTIC_APM_GLOBAL_LABELS=mykey1=myvalue1,mykey2=myvalue2

      # Print Elastic agent logs on screen
      # - ELASTIC_APM_LOG_FILE=stdout
      # Set Elastic agent log level to debug if needed to see detailed logs
      # - ELASTIC_APM_LOG_LEVEL=debug
    ports:
      - "8000:8000"
    depends_on:
      - mysql
      - redis
    restart: always

  mysql:
    image: mysql:8.0
    container_name: cube_nodejs_fastify_mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=test
    volumes:
      - cube_nodejs_fastify_mysql:/var/lib/mysql
    ports:
      - "3306:3306"

  redis:
    image: redis:alpine3.18
    container_name: cube_nodejs_fastify_redis

volumes:
  cube_nodejs_fastify_mysql:
